name: Android CI - VeeStores Browser

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 9.1.0

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-levels: 34
        build-tools: 34.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --stacktrace

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VeeStores-Browser-APK
        path: app/build/outputs/apk/debug/app-debug.apk
